[package]

name = "kindlegen-as-a-service"
version = "0.0.1"
authors = [ "Dan Berglund <dan@berglund.io" ]

[dependencies]
rouille = "3.0.0"
uuid = { version = "0.8", features = ["v4"] }
log = "0.4.13"
simple_logger = "2.0.0"
